<?php
require_once __DIR__ . '/includes/auth.php'; require_auth();
$id=(int)($_GET['id']??0);$asset=get_asset($id);$u=current_user();
if(!$asset||!asset_can_view($asset,$u)){http_response_code(404);exit('Asset not found.');}
$canManage=asset_can_manage($asset,$u);
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=(string)($_POST['action']??'');
 if($action==='favorite'){db()->prepare('INSERT IGNORE INTO favorites(user_id,asset_id) VALUES(?,?)')->execute([$u['id'],$id]);flash('success','Added to favorites.');}
 elseif($action==='unfavorite'){db()->prepare('DELETE FROM favorites WHERE user_id=? AND asset_id=?')->execute([$u['id'],$id]);flash('success','Removed from favorites.');}
 elseif($action==='add_collection'){ $cid=(int)($_POST['collection_id']??0);$check=db()->prepare('SELECT id FROM collections WHERE id=? AND owner_id=?');$check->execute([$cid,$u['id']]);if(!$check->fetch())flash('danger','Collection not found.');else{db()->prepare('INSERT IGNORE INTO collection_assets(collection_id,asset_id,added_by) VALUES(?,?,?)')->execute([$cid,$id,$u['id']]);flash('success','Asset added to collection.');}}
 elseif(in_array($action,['archive','unarchive','delete'],true)&&$canManage){if($action==='delete'){db()->prepare('UPDATE assets SET deleted_at=NOW() WHERE id=?')->execute([$id]);audit('asset_deleted','Moved asset “'.$asset['title'].'” to the Recycle Bin.');flash('success','Asset moved to the Recycle Bin.');redirect('assets.php');}else{$new=$action==='archive'?'archived':'active';db()->prepare('UPDATE assets SET status=? WHERE id=?')->execute([$new,$id]);audit('asset_'.$action,ucfirst($action).'d asset “'.$asset['title'].'”.');flash('success','Asset status updated.');}}
 elseif($action==='create_share'&&$canManage&&setting('public_sharing_enabled','1')==='1'){ $days=max(1,min(365,(int)($_POST['expiry_days']??setting('default_share_expiry_days',7))));$token=bin2hex(random_bytes(32));$password=trim((string)($_POST['share_password']??''));$hash=$password!==''?password_hash($password,PASSWORD_DEFAULT):null;$download=isset($_POST['download_allowed'])?1:0;db()->prepare('INSERT INTO share_links(asset_id,created_by,token,password_hash,expires_at,download_allowed) VALUES(?,?,?,?,DATE_ADD(NOW(),INTERVAL ? DAY),?)')->execute([$id,$u['id'],$token,$hash,$days,$download]);audit('asset_shared','Created a share link for “'.$asset['title'].'”.');flash('success','Secure share link created.');}
 elseif($action==='disable_share'&&$canManage){$sid=(int)($_POST['share_id']??0);db()->prepare('UPDATE share_links SET is_active=0 WHERE id=? AND asset_id=?')->execute([$sid,$id]);flash('success','Share link disabled.');}
 elseif($action==='new_version'&&$canManage){try{$upload=safe_upload($_FILES['version_file']??[]);$next=round((float)$asset['version_number']+1,2);db()->beginTransaction();db()->prepare('INSERT INTO asset_versions(asset_id,version_number,original_filename,stored_filename,file_path,file_extension,mime_type,file_size,uploaded_by,version_notes) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$id,$next,$upload['original'],$upload['stored'],$upload['relative'],$upload['extension'],$upload['mime'],$upload['size'],$u['id'],trim((string)($_POST['version_notes']??''))]);db()->prepare('UPDATE assets SET original_filename=?,stored_filename=?,file_path=?,file_extension=?,mime_type=?,file_size=?,version_number=? WHERE id=?')->execute([$upload['original'],$upload['stored'],$upload['relative'],$upload['extension'],$upload['mime'],$upload['size'],$next,$id]);db()->commit();audit('asset_versioned','Uploaded version '.$next.' of “'.$asset['title'].'”.');flash('success','New version uploaded.');}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();if(isset($upload))delete_stored_file($upload['relative']);flash('danger',$e instanceof PDOException?'Could not save the version.':$e->getMessage());}}
 redirect('asset-details.php?id='.$id);
}
$asset=get_asset($id);$tags=tags_for_asset($id);$favoriteStmt=db()->prepare('SELECT 1 FROM favorites WHERE user_id=? AND asset_id=?');$favoriteStmt->execute([$u['id'],$id]);$isFavorite=(bool)$favoriteStmt->fetchColumn();
$collectionsStmt=db()->prepare('SELECT id,name FROM collections WHERE owner_id=? ORDER BY name');$collectionsStmt->execute([$u['id']]);$collections=$collectionsStmt->fetchAll();
$versionsStmt=db()->prepare('SELECT v.*,u.name uploader_name FROM asset_versions v JOIN users u ON u.id=v.uploaded_by WHERE v.asset_id=? ORDER BY v.version_number DESC');$versionsStmt->execute([$id]);$versions=$versionsStmt->fetchAll();
$shares=[];if($canManage){$s=db()->prepare('SELECT * FROM share_links WHERE asset_id=? ORDER BY created_at DESC');$s->execute([$id]);$shares=$s->fetchAll();}
$pageTitle=$asset['title'];$pageSubtitle=$asset['asset_code'];$pageActions='<a class="btn btn-primary" href="'.e(url('download.php?id='.$id)).'"><i class="bi bi-download me-1"></i>Download</a>';
require __DIR__.'/includes/header.php';
?>
<div class="row g-4"><div class="col-xl-8"><div class="card mb-4"><div class="card-body p-3"><div class="preview-stage"><?php if(in_array($asset['file_extension'],['jpg','jpeg','png','gif','webp','svg'],true)):?><img src="<?=e(url('preview.php?id='.$id))?>" alt="<?=e($asset['title'])?>"><?php elseif($asset['file_extension']==='pdf'):?><iframe src="<?=e(url('preview.php?id='.$id))?>" width="100%" height="600" title="PDF preview"></iframe><?php elseif(in_array($asset['file_extension'],['mp4','webm'],true)):?><video controls preload="metadata" src="<?=e(url('preview.php?id='.$id))?>"></video><?php elseif(in_array($asset['file_extension'],['mp3','wav'],true)):?><div class="text-center w-75"><i class="bi bi-file-music display-1 text-primary"></i><audio class="w-100 mt-4" controls src="<?=e(url('preview.php?id='.$id))?>"></audio></div><?php else:?><div class="text-center"><i class="bi <?=e(asset_icon($asset['file_extension']))?> display-1 text-primary"></i><h2 class="h5 mt-3"><?=e($asset['original_filename'])?></h2><p class="text-muted text-uppercase"><?=e($asset['file_extension'])?> · <?=e(human_file_size((int)$asset['file_size']))?></p><a class="btn btn-primary" href="<?=e(url('download.php?id='.$id))?>">Download to view</a></div><?php endif;?></div></div></div>
<div class="card mb-4"><div class="card-header bg-white py-3"><h2 class="h6 mb-0">About this asset</h2></div><div class="card-body"><p class="mb-4"><?=nl2br(e($asset['description']?:'No description provided.'))?></p><div class="d-flex flex-wrap gap-2"><?php foreach($tags as $tag):?><a class="badge rounded-pill text-bg-light text-decoration-none" href="<?=e(url('assets.php?tag='.urlencode($tag['name'])))?>">#<?=e($tag['name'])?></a><?php endforeach;?></div></div></div>
<div class="card"><div class="card-header bg-white d-flex justify-content-between align-items-center py-3"><h2 class="h6 mb-0">Version history</h2><?php if($canManage):?><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#versionModal"><i class="bi bi-plus-lg"></i> New version</button><?php endif;?></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Version</th><th>File</th><th>Uploaded by</th><th>Date</th><th>Notes</th><th></th></tr></thead><tbody><?php foreach($versions as $v):?><tr><td><span class="badge text-bg-light">v<?=e(rtrim(rtrim($v['version_number'],'0'),'.'))?></span></td><td><?=e($v['original_filename'])?><small class="d-block text-muted"><?=e(human_file_size((int)$v['file_size']))?></small></td><td><?=e($v['uploader_name'])?></td><td><?=e(date('M j, Y',strtotime($v['created_at'])))?></td><td><?=e($v['version_notes']?:'—')?></td><td><a class="btn btn-sm btn-light" href="<?=e(url('download.php?id='.$id.'&version='.$v['id']))?>"><i class="bi bi-download"></i></a></td></tr><?php endforeach;?></tbody></table></div></div></div>
<div class="col-xl-4"><div class="card mb-4"><div class="card-body"><div class="d-flex gap-2 mb-4"><?php if($canManage):?><a class="btn btn-outline-primary flex-fill" href="<?=e(url('edit-asset.php?id='.$id))?>"><i class="bi bi-pencil me-1"></i>Edit</a><?php endif;?><form method="post" class="flex-fill"><?=csrf_field()?><input type="hidden" name="action" value="<?=$isFavorite?'unfavorite':'favorite'?>"><button class="btn btn-outline-warning w-100"><i class="bi bi-star<?=$isFavorite?'-fill':''?> me-1"></i><?=$isFavorite?'Saved':'Favorite'?></button></form></div><dl class="row small mb-0"><dt class="col-5 text-muted fw-normal">Original name</dt><dd class="col-7 text-break"><?=e($asset['original_filename'])?></dd><dt class="col-5 text-muted fw-normal">Type</dt><dd class="col-7"><?=e($asset['mime_type'])?></dd><dt class="col-5 text-muted fw-normal">Size</dt><dd class="col-7"><?=e(human_file_size((int)$asset['file_size']))?></dd><?php if($asset['width']):?><dt class="col-5 text-muted fw-normal">Dimensions</dt><dd class="col-7"><?=$asset['width']?> × <?=$asset['height']?> px</dd><?php endif;?><dt class="col-5 text-muted fw-normal">Category</dt><dd class="col-7"><?=e($asset['category_name']??'Uncategorized')?></dd><dt class="col-5 text-muted fw-normal">Uploaded by</dt><dd class="col-7"><?=e($asset['uploader_name'])?></dd><dt class="col-5 text-muted fw-normal">Uploaded</dt><dd class="col-7"><?=e(date('M j, Y g:i A',strtotime($asset['created_at'])))?></dd><dt class="col-5 text-muted fw-normal">Modified</dt><dd class="col-7"><?=e(date('M j, Y g:i A',strtotime($asset['updated_at'])))?></dd><dt class="col-5 text-muted fw-normal">Downloads</dt><dd class="col-7"><?=number_format((int)$asset['download_count'])?></dd><dt class="col-5 text-muted fw-normal">Version</dt><dd class="col-7">v<?=e(rtrim(rtrim($asset['version_number'],'0'),'.'))?></dd><dt class="col-5 text-muted fw-normal">Visibility</dt><dd class="col-7 text-capitalize"><?=e($asset['visibility'])?></dd><dt class="col-5 text-muted fw-normal">Status</dt><dd class="col-7 text-capitalize"><?=e($asset['status'])?></dd></dl></div></div>
<?php if($collections):?><div class="card mb-4"><div class="card-body"><h2 class="h6">Add to collection</h2><form method="post" class="d-flex gap-2"><?=csrf_field()?><input type="hidden" name="action" value="add_collection"><select class="form-select" name="collection_id" required><option value="">Choose…</option><?php foreach($collections as $c):?><option value="<?=$c['id']?>"><?=e($c['name'])?></option><?php endforeach;?></select><button class="btn btn-primary">Add</button></form></div></div><?php endif;?>
<?php if($canManage):?><div class="card mb-4"><div class="card-body"><h2 class="h6">Share asset</h2><?php if(setting('public_sharing_enabled','1')==='1'):?><form method="post" class="row g-2 mb-3"><?=csrf_field()?><input type="hidden" name="action" value="create_share"><div class="col-6"><input class="form-control" type="number" min="1" max="365" name="expiry_days" value="<?=e(setting('default_share_expiry_days',7))?>" aria-label="Expiry days"></div><div class="col-6"><input class="form-control" name="share_password" placeholder="Password (optional)"></div><div class="col-8"><div class="form-check mt-2"><input class="form-check-input" type="checkbox" name="download_allowed" id="downloadAllowed" checked><label class="form-check-label" for="downloadAllowed">Allow downloads</label></div></div><div class="col-4"><button class="btn btn-primary w-100">Create</button></div></form><?php else:?><div class="alert alert-warning small">Public sharing is disabled in Settings.</div><?php endif;?><?php foreach($shares as $s):$shareUrl=url('share.php?token='.$s['token']);?><div class="border rounded p-2 mb-2"><div class="d-flex gap-2"><input class="form-control form-control-sm" readonly value="<?=e($shareUrl)?>"><button class="btn btn-sm btn-light" type="button" data-copy="<?=e($shareUrl)?>"><i class="bi bi-copy"></i></button></div><small class="text-muted"><?=$s['is_active']?'Active':'Disabled'?> · expires <?=e($s['expires_at']?date('M j, Y',strtotime($s['expires_at'])):'never')?> · <?=$s['download_allowed']?'downloads allowed':'view only'?></small><?php if($s['is_active']):?><form method="post" class="mt-1"><?=csrf_field()?><input type="hidden" name="action" value="disable_share"><input type="hidden" name="share_id" value="<?=$s['id']?>"><button class="btn btn-link text-danger btn-sm p-0">Disable</button></form><?php endif;?></div><?php endforeach;?></div></div>
<div class="card border-danger"><div class="card-body"><h2 class="h6">Asset lifecycle</h2><div class="d-grid gap-2"><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="<?=$asset['status']==='archived'?'unarchive':'archive'?>"><button class="btn btn-outline-secondary w-100"><?=$asset['status']==='archived'?'Restore from archive':'Archive asset'?></button></form><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="delete"><button class="btn btn-outline-danger w-100" data-confirm="Move this asset to the Recycle Bin?">Move to Recycle Bin</button></form></div></div></div><?php endif;?></div></div>
<?php if($canManage):?><div class="modal fade" id="versionModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post" enctype="multipart/form-data"><?=csrf_field()?><input type="hidden" name="action" value="new_version"><div class="modal-header"><h2 class="modal-title fs-5">Upload new version</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Replacement file</label><input class="form-control mb-3" type="file" name="version_file" required><label class="form-label">Version notes</label><textarea class="form-control" name="version_notes" rows="3"></textarea></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Upload version</button></div></form></div></div></div><?php endif;?>
<?php require __DIR__.'/includes/footer.php';?>

