<?php
require_once __DIR__.'/includes/auth.php';require_role(['Administrator','Asset Manager']);$u=current_user();
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=(string)($_POST['action']??'');
 try{if($action==='save_category'){ $cid=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));$parent=(int)($_POST['parent_id']??0)?:null;if($name==='')throw new RuntimeException('Category name is required.');if($cid&&$parent===$cid)throw new RuntimeException('A category cannot be its own parent.');if($cid){db()->prepare('UPDATE categories SET name=?,description=?,parent_id=? WHERE id=?')->execute([mb_substr($name,0,100),trim((string)($_POST['description']??'')),$parent,$cid]);audit('category_updated','Updated category “'.$name.'”.');}else{db()->prepare('INSERT INTO categories(name,description,parent_id,created_by) VALUES(?,?,?,?)')->execute([mb_substr($name,0,100),trim((string)($_POST['description']??'')),$parent,$u['id']]);audit('category_created','Created category “'.$name.'”.');}flash('success','Category saved.');}
 elseif($action==='delete_category'){db()->prepare('DELETE FROM categories WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Category deleted; its assets are now uncategorized.');}
 elseif($action==='save_tag'){ $name=mb_strtolower(trim((string)($_POST['name']??'')));if($name==='')throw new RuntimeException('Tag name is required.');db()->prepare('INSERT INTO tags(name,created_by) VALUES(?,?) ON DUPLICATE KEY UPDATE name=VALUES(name)')->execute([mb_substr($name,0,80),$u['id']]);flash('success','Tag saved.');}
 elseif($action==='delete_tag'){db()->prepare('DELETE FROM tags WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Tag deleted.');}}
 catch(Throwable $e){flash('danger',$e instanceof PDOException?'That name is already in use or the item cannot be deleted.':$e->getMessage());}redirect('categories.php');}
$categories=db()->query('SELECT c.*,p.name parent_name,COUNT(a.id) asset_count FROM categories c LEFT JOIN categories p ON p.id=c.parent_id LEFT JOIN assets a ON a.category_id=c.id AND a.deleted_at IS NULL GROUP BY c.id ORDER BY COALESCE(p.name,c.name),c.parent_id,c.name')->fetchAll();$tags=db()->query('SELECT t.*,COUNT(at.asset_id) asset_count FROM tags t LEFT JOIN asset_tags at ON at.tag_id=t.id GROUP BY t.id ORDER BY t.name')->fetchAll();$pageTitle='Categories & tags';$pageSubtitle='Maintain reusable metadata for consistent organization';require __DIR__.'/includes/header.php';?>
<div class="row g-4"><div class="col-xl-8"><div class="card mb-4"><div class="card-header bg-white py-3"><h2 class="h6 mb-0">Categories</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Name</th><th>Parent</th><th>Description</th><th>Assets</th><th></th></tr></thead><tbody><?php foreach($categories as $c):?><tr><td class="fw-semibold"><?=e($c['name'])?></td><td><?=e($c['parent_name']??'—')?></td><td><?=e($c['description']?:'—')?></td><td><?=$c['asset_count']?></td><td class="text-end"><button class="btn btn-sm btn-light edit-category" data-record="<?=e(json_encode(['id'=>$c['id'],'name'=>$c['name'],'description'=>$c['description'],'parent_id'=>$c['parent_id']],JSON_HEX_APOS|JSON_HEX_QUOT))?>">Edit</button><form method="post" class="d-inline"><?=csrf_field()?><input type="hidden" name="action" value="delete_category"><input type="hidden" name="id" value="<?=$c['id']?>"><button class="btn btn-sm btn-light text-danger" data-confirm="Delete this category?">Delete</button></form></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="card"><div class="card-header bg-white py-3"><h2 class="h6 mb-0">Reusable tags</h2></div><div class="card-body d-flex flex-wrap gap-2"><?php foreach($tags as $tag):?><span class="badge rounded-pill text-bg-light p-2">#<?=e($tag['name'])?> <span class="text-muted"><?=$tag['asset_count']?></span><form method="post" class="d-inline"><?=csrf_field()?><input type="hidden" name="action" value="delete_tag"><input type="hidden" name="id" value="<?=$tag['id']?>"><button class="border-0 bg-transparent text-danger p-0 ms-1" title="Delete tag">×</button></form></span><?php endforeach;?><?php if(!$tags):?><span class="text-muted">Tags appear here after they are added to assets.</span><?php endif;?></div></div></div>
<div class="col-xl-4"><div class="card mb-4"><div class="card-body"><h2 class="h6" id="categoryFormTitle">Add category</h2><form method="post" id="categoryForm"><?=csrf_field()?><input type="hidden" name="action" value="save_category"><input type="hidden" name="id" id="categoryId"><label class="form-label">Name</label><input class="form-control mb-3" name="name" id="categoryName" required><label class="form-label">Parent category</label><select class="form-select mb-3" name="parent_id" id="categoryParent"><option value="">None</option><?php foreach($categories as $c):?><option value="<?=$c['id']?>"><?=e($c['name'])?></option><?php endforeach;?></select><label class="form-label">Description</label><textarea class="form-control mb-3" name="description" id="categoryDescription" rows="3"></textarea><button class="btn btn-primary">Save category</button><button type="button" class="btn btn-light" id="resetCategory">Clear</button></form></div></div><div class="card"><div class="card-body"><h2 class="h6">Create tag</h2><form method="post" class="d-flex gap-2"><?=csrf_field()?><input type="hidden" name="action" value="save_tag"><input class="form-control" name="name" placeholder="e.g. campaign" required><button class="btn btn-primary">Add</button></form></div></div></div></div>
<?php $extraScripts='<script>const reset=()=>{categoryForm.reset();categoryId.value="";categoryFormTitle.textContent="Add category"};document.querySelectorAll(".edit-category").forEach(b=>b.onclick=()=>{const r=JSON.parse(b.dataset.record);categoryId.value=r.id;categoryName.value=r.name;categoryDescription.value=r.description||"";categoryParent.value=r.parent_id||"";categoryFormTitle.textContent="Edit category";scrollTo({top:0,behavior:"smooth"})});resetCategory.onclick=reset;</script>';require __DIR__.'/includes/footer.php';?>

