<?php
require_once __DIR__ . '/includes/auth.php'; require_auth();
$pageTitle='Dashboard'; $pageSubtitle='A live overview of your digital asset library'; $u=current_user();
$uid=(int)$u['id'];
$scope = $u['role_name']==='Administrator' ? '1=1' : "(a.visibility IN ('organization','public') OR a.uploaded_by={$uid} OR EXISTS(SELECT 1 FROM collection_assets ca4 JOIN collections c4 ON c4.id=ca4.collection_id LEFT JOIN collection_shares cs4 ON cs4.collection_id=c4.id AND cs4.user_id={$uid} WHERE ca4.asset_id=a.id AND (c4.owner_id={$uid} OR c4.visibility='organization' OR cs4.user_id IS NOT NULL)))";
$assetWhere="a.deleted_at IS NULL AND {$scope}";
$stats=db()->query("SELECT COUNT(*) total_assets,COALESCE(SUM(a.file_size),0) storage,COALESCE(SUM(a.download_count),0) downloads,SUM(DATE(a.created_at)=CURDATE()) today,SUM(YEAR(a.created_at)=YEAR(CURDATE()) AND MONTH(a.created_at)=MONTH(CURDATE())) month,SUM(a.status='archived') archived,SUM(a.file_extension IN ('jpg','jpeg','png','gif','webp','svg')) images,SUM(a.file_extension IN ('mp4','webm')) videos,SUM(a.file_extension IN ('mp3','wav')) audio,SUM(a.file_extension IN ('pdf','doc','docx','xls','xlsx','ppt','pptx','txt','csv')) documents FROM assets a WHERE {$assetWhere}")->fetch();
$userCount=$u['role_name']==='Administrator'?(int)db()->query("SELECT COUNT(*) FROM users WHERE deleted_at IS NULL")->fetchColumn():null;
$months=[]; for($i=5;$i>=0;$i--){$key=date('Y-m',strtotime("-{$i} months"));$months[$key]=['label'=>date('M Y',strtotime($key.'-01')),'uploads'=>0,'downloads'=>0];}
foreach(db()->query("SELECT DATE_FORMAT(created_at,'%Y-%m') ym,COUNT(*) c FROM assets WHERE deleted_at IS NULL AND created_at>=DATE_SUB(CURDATE(),INTERVAL 6 MONTH) GROUP BY ym") as $r)if(isset($months[$r['ym']]))$months[$r['ym']]['uploads']=(int)$r['c'];
foreach(db()->query("SELECT DATE_FORMAT(downloaded_at,'%Y-%m') ym,COUNT(*) c FROM downloads WHERE downloaded_at>=DATE_SUB(CURDATE(),INTERVAL 6 MONTH) GROUP BY ym") as $r)if(isset($months[$r['ym']]))$months[$r['ym']]['downloads']=(int)$r['c'];
$types=db()->query("SELECT CASE WHEN file_extension IN ('jpg','jpeg','png','gif','webp','svg') THEN 'Images' WHEN file_extension IN ('mp4','webm') THEN 'Videos' WHEN file_extension IN ('mp3','wav') THEN 'Audio' WHEN file_extension='zip' THEN 'Archives' ELSE 'Documents' END label,COUNT(*) value FROM assets a WHERE {$assetWhere} GROUP BY label")->fetchAll();
$categories=db()->query("SELECT COALESCE(c.name,'Uncategorized') label,COUNT(*) value FROM assets a LEFT JOIN categories c ON c.id=a.category_id WHERE {$assetWhere} GROUP BY c.id,c.name ORDER BY value DESC LIMIT 7")->fetchAll();
$storageGroups=db()->query("SELECT CASE WHEN file_extension IN ('jpg','jpeg','png','gif','webp','svg') THEN 'Images' WHEN file_extension IN ('mp4','webm') THEN 'Videos' WHEN file_extension IN ('mp3','wav') THEN 'Audio' WHEN file_extension='zip' THEN 'Archives' ELSE 'Documents' END label,SUM(file_size) value FROM assets a WHERE {$assetWhere} GROUP BY label")->fetchAll();
$recent=db()->query("SELECT a.*,u.name uploader_name,c.name category_name FROM assets a JOIN users u ON u.id=a.uploaded_by LEFT JOIN categories c ON c.id=a.category_id WHERE {$assetWhere} ORDER BY a.created_at DESC LIMIT 6")->fetchAll();
$most=db()->query("SELECT a.id,a.title,a.file_extension,a.download_count FROM assets a WHERE {$assetWhere} ORDER BY a.download_count DESC,a.created_at DESC LIMIT 5")->fetchAll();
$largest=db()->query("SELECT a.id,a.title,a.file_extension,a.file_size FROM assets a WHERE {$assetWhere} ORDER BY a.file_size DESC LIMIT 5")->fetchAll();
$recentDownloads=db()->query("SELECT d.downloaded_at,a.id,a.title,u.name user_name FROM downloads d JOIN assets a ON a.id=d.asset_id LEFT JOIN users u ON u.id=d.user_id WHERE {$assetWhere} ORDER BY d.downloaded_at DESC LIMIT 5")->fetchAll();
$activity=$u['role_name']==='Administrator'?db()->query("SELECT l.*,u.name user_name FROM activity_logs l LEFT JOIN users u ON u.id=l.user_id ORDER BY l.created_at DESC LIMIT 7")->fetchAll():[];
$pageActions=in_array($u['role_name'],['Administrator','Asset Manager'],true)?'<a class="btn btn-primary" href="'.e(url('upload.php')).'"><i class="bi bi-cloud-arrow-up me-2"></i>Upload assets</a>':'';
require __DIR__.'/includes/header.php';
$cards=[['Total assets',$stats['total_assets'],'bi-folder2-open','primary'],['Storage used',human_file_size((int)$stats['storage']),'bi-device-ssd','info'],['Total downloads',$stats['downloads'],'bi-download','success'],[$userCount!==null?'Total users':'Uploaded this month',$userCount??$stats['month'],$userCount!==null?'bi-people':'bi-calendar3','warning']];
?>
<div class="row g-3 mb-4"><?php foreach($cards as [$label,$value,$icon,$color]):?><div class="col-sm-6 col-xl-3"><div class="card stat-card h-100"><div class="card-body d-flex justify-content-between"><div><div class="text-muted small mb-2"><?=e($label)?></div><div class="stat-value"><?=e($value)?></div></div><div class="stat-icon bg-<?=$color?> bg-opacity-10 text-<?=$color?>"><i class="bi <?=e($icon)?>"></i></div></div></div></div><?php endforeach;?></div>
<div class="row g-4 mb-4"><div class="col-xl-8"><div class="card h-100"><div class="card-header bg-white border-0 pt-4 px-4"><h2 class="h6 mb-0">Uploads & downloads</h2></div><div class="card-body"><div class="chart-wrap"><canvas id="trendChart"></canvas></div></div></div></div><div class="col-xl-4"><div class="card h-100"><div class="card-header bg-white border-0 pt-4 px-4"><h2 class="h6 mb-0">Assets by type</h2></div><div class="card-body"><div class="chart-wrap"><canvas id="typeChart"></canvas></div></div></div></div></div>
<div class="row g-4 mb-4"><div class="col-xl-7"><div class="card h-100"><div class="card-header bg-white border-0 pt-4 px-4"><h2 class="h6 mb-0">Assets by category</h2></div><div class="card-body"><div class="chart-wrap"><canvas id="categoryChart"></canvas></div></div></div></div><div class="col-xl-5"><div class="card h-100"><div class="card-header bg-white border-0 pt-4 px-4"><h2 class="h6 mb-0">Storage usage</h2></div><div class="card-body"><div class="chart-wrap"><canvas id="storageChart"></canvas></div></div></div></div></div>
<div class="row g-4 mb-4"><div class="col-xl-8"><div class="card"><div class="card-header bg-white d-flex justify-content-between align-items-center py-3"><h2 class="h6 mb-0">Recent uploads</h2><a class="small text-decoration-none" href="<?=e(url('assets.php'))?>">View library</a></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Asset</th><th>Category</th><th>Size</th><th>Uploaded</th></tr></thead><tbody><?php foreach($recent as $a):?><tr><td><a class="text-decoration-none fw-semibold" href="<?=e(url('asset-details.php?id='.$a['id']))?>"><i class="bi <?=e(asset_icon($a['file_extension']))?> me-2 text-primary"></i><?=e($a['title'])?></a><small class="d-block text-muted ms-4"><?=e($a['uploader_name'])?></small></td><td><?=e($a['category_name']??'—')?></td><td><?=e(human_file_size((int)$a['file_size']))?></td><td><span title="<?=e($a['created_at'])?>"><?=e(date('M j',strtotime($a['created_at'])))?></span></td></tr><?php endforeach;?><?php if(!$recent):?><tr><td colspan="4" class="empty-state">No assets yet.</td></tr><?php endif;?></tbody></table></div></div></div><div class="col-xl-4"><div class="card mb-4"><div class="card-header bg-white py-3"><h2 class="h6 mb-0">Most downloaded</h2></div><div class="list-group list-group-flush"><?php foreach($most as $i=>$a):?><a class="list-group-item list-group-item-action d-flex align-items-center gap-3 py-3" href="<?=e(url('asset-details.php?id='.$a['id']))?>"><span class="badge rounded-pill text-bg-light"><?=($i+1)?></span><span class="flex-grow-1 text-truncate"><?=e($a['title'])?></span><span class="small text-muted"><?=number_format((int)$a['download_count'])?></span></a><?php endforeach;?><?php if(!$most):?><div class="p-4 text-muted">No downloads yet.</div><?php endif;?></div></div><div class="card"><div class="card-body"><div class="row text-center g-2"><div class="col"><strong class="d-block"><?=number_format((int)$stats['images'])?></strong><small class="text-muted">Images</small></div><div class="col"><strong class="d-block"><?=number_format((int)$stats['videos'])?></strong><small class="text-muted">Videos</small></div><div class="col"><strong class="d-block"><?=number_format((int)$stats['documents'])?></strong><small class="text-muted">Docs</small></div><div class="col"><strong class="d-block"><?=number_format((int)$stats['archived'])?></strong><small class="text-muted">Archived</small></div></div></div></div></div></div>
<?php if($activity):?><div class="card"><div class="card-header bg-white py-3"><h2 class="h6 mb-0">Recent activity</h2></div><div class="table-responsive"><table class="table mb-0"><tbody><?php foreach($activity as $row):?><tr><td class="text-muted" style="width:150px"><?=e(date('M j, g:i A',strtotime($row['created_at'])))?></td><td><strong><?=e($row['user_name']??'System')?></strong> <?=e($row['description'])?></td></tr><?php endforeach;?></tbody></table></div></div><?php endif;?>
<div class="row g-4 my-1"><div class="col-xl-6"><div class="card"><div class="card-header bg-white py-3"><h2 class="h6 mb-0">Recent downloads</h2></div><div class="list-group list-group-flush"><?php foreach($recentDownloads as $row):?><a class="list-group-item list-group-item-action d-flex justify-content-between py-3" href="<?=e(url('asset-details.php?id='.$row['id']))?>"><span><?=e($row['title'])?><small class="d-block text-muted"><?=e($row['user_name']??'Public share')?></small></span><small class="text-muted"><?=e(date('M j, g:i A',strtotime($row['downloaded_at'])))?></small></a><?php endforeach;?><?php if(!$recentDownloads):?><div class="p-4 text-muted">No downloads yet.</div><?php endif;?></div></div></div><div class="col-xl-6"><div class="card"><div class="card-header bg-white py-3"><h2 class="h6 mb-0">Largest assets</h2></div><div class="list-group list-group-flush"><?php foreach($largest as $row):?><a class="list-group-item list-group-item-action d-flex justify-content-between py-3" href="<?=e(url('asset-details.php?id='.$row['id']))?>"><span><i class="bi <?=e(asset_icon($row['file_extension']))?> me-2 text-primary"></i><?=e($row['title'])?></span><strong class="small"><?=e(human_file_size((int)$row['file_size']))?></strong></a><?php endforeach;?></div></div></div></div>
<?php $extraScripts='<script>const colors=["#5b5bd6","#06b6d4","#10b981","#f59e0b","#ef4444","#8b5cf6","#64748b"];new Chart(document.getElementById("trendChart"),{type:"line",data:{labels:'.json_encode(array_column($months,'label')).',datasets:[{label:"Uploads",data:'.json_encode(array_column($months,'uploads')).',borderColor:"#5b5bd6",backgroundColor:"rgba(91,91,214,.12)",fill:true,tension:.35},{label:"Downloads",data:'.json_encode(array_column($months,'downloads')).',borderColor:"#10b981",backgroundColor:"rgba(16,185,129,.08)",tension:.35}]},options:{maintainAspectRatio:false,plugins:{legend:{position:"bottom"}},scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});new Chart(document.getElementById("typeChart"),{type:"doughnut",data:{labels:'.json_encode(array_column($types,'label')).',datasets:[{data:'.json_encode(array_column($types,'value')).',backgroundColor:colors}]},options:{maintainAspectRatio:false,plugins:{legend:{position:"bottom"}},cutout:"68%"}});new Chart(document.getElementById("categoryChart"),{type:"bar",data:{labels:'.json_encode(array_column($categories,'label')).',datasets:[{label:"Assets",data:'.json_encode(array_column($categories,'value')).',backgroundColor:"#5b5bd6"}]},options:{maintainAspectRatio:false,indexAxis:"y",plugins:{legend:{display:false}},scales:{x:{beginAtZero:true,ticks:{precision:0}}}}});new Chart(document.getElementById("storageChart"),{type:"doughnut",data:{labels:'.json_encode(array_column($storageGroups,'label')).',datasets:[{data:'.json_encode(array_map('intval',array_column($storageGroups,'value'))).',backgroundColor:colors}]},options:{maintainAspectRatio:false,plugins:{legend:{position:"bottom"}},cutout:"62%"}});</script>'; require __DIR__.'/includes/footer.php';?>
