<?php
require_once __DIR__ . '/includes/auth.php'; require_role(['Administrator','Asset Manager']);
$pageTitle='Upload assets'; $pageSubtitle='Add files securely to your organization’s library';
$categories=db()->query('SELECT id,name FROM categories ORDER BY name')->fetchAll();
require __DIR__.'/includes/header.php';
?>
<div class="row g-4"><div class="col-xl-8"><div class="card"><div class="card-body p-4"><div id="dropZone" class="drop-zone"><div><i class="bi bi-cloud-arrow-up display-4 text-primary"></i><h2 class="h5 mt-3">Drop files here to upload</h2><p class="text-muted mb-3">or choose files from your computer</p><button type="button" class="btn btn-primary" id="browseButton">Choose files</button><input type="file" id="fileInput" multiple hidden accept="<?=e('.'.implode(',.',allowed_extensions()))?>"><div class="small text-muted mt-3">Maximum <?=e(human_file_size(max_upload_bytes()))?> per file</div></div></div><div id="fileQueue" class="d-grid gap-2 mt-4"></div></div></div></div>
<div class="col-xl-4"><div class="card"><div class="card-body p-4"><h2 class="h6 mb-3">Asset information</h2><div class="mb-3"><label class="form-label">Category</label><select class="form-select" id="category"><option value="">Uncategorized</option><?php foreach($categories as $c):?><option value="<?=$c['id']?>"><?=e($c['name'])?></option><?php endforeach;?></select></div><div class="mb-3"><label class="form-label">Description</label><textarea class="form-control" id="description" rows="3" placeholder="Applied to all selected files"></textarea></div><div class="mb-3"><label class="form-label">Tags</label><input class="form-control" id="tags" placeholder="campaign, 2026, product"><div class="form-text">Separate reusable tags with commas.</div></div><div class="mb-4"><label class="form-label">Visibility</label><select class="form-select" id="visibility"><option value="organization">Organization</option><option value="private">Private</option><option value="public">Public</option></select></div><button class="btn btn-primary w-100" id="uploadButton" disabled><i class="bi bi-cloud-arrow-up me-2"></i>Upload selected files</button><div id="uploadSummary" class="mt-3"></div></div></div></div></div>
<?php
$extraScripts=<<<'HTML'
<script>
(()=>{const zone=document.querySelector('#dropZone'),input=document.querySelector('#fileInput'),queue=document.querySelector('#fileQueue'),upload=document.querySelector('#uploadButton');let files=[];
const fmt=n=>{const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]};
function draw(){queue.innerHTML='';files.forEach((f,i)=>{const el=document.createElement('div');el.className='file-queue-item';el.innerHTML=`<div class="stat-icon bg-primary bg-opacity-10 text-primary"><i class="bi bi-file-earmark"></i></div><div class="overflow-hidden"><strong class="d-block text-truncate"></strong><small class="text-muted">${fmt(f.size)}</small><div class="progress mt-2 d-none" style="height:5px"><div class="progress-bar" style="width:0"></div></div><small class="status"></small></div><button class="btn btn-sm btn-light text-danger" type="button"><i class="bi bi-x-lg"></i></button>`;el.querySelector('strong').textContent=f.name;el.querySelector('button').onclick=()=>{files.splice(i,1);draw()};queue.append(el)});upload.disabled=!files.length}
function add(list){for(const f of list){if(!files.some(x=>x.name===f.name&&x.size===f.size))files.push(f)}draw()}
document.querySelector('#browseButton').onclick=()=>input.click();input.onchange=()=>add(input.files);['dragenter','dragover'].forEach(n=>zone.addEventListener(n,e=>{e.preventDefault();zone.classList.add('dragover')}));['dragleave','drop'].forEach(n=>zone.addEventListener(n,e=>{e.preventDefault();zone.classList.remove('dragover')}));zone.addEventListener('drop',e=>add(e.dataTransfer.files));
upload.onclick=async()=>{upload.disabled=true;let ok=0,failed=0;for(let i=0;i<files.length;i++){const row=queue.children[i],progress=row.querySelector('.progress'),bar=row.querySelector('.progress-bar'),status=row.querySelector('.status');progress.classList.remove('d-none');const data=new FormData();data.append('csrf_token',document.querySelector('meta[name="csrf-token"]').content);data.append('file',files[i]);data.append('title',files[i].name.replace(/\.[^.]+$/,''));data.append('category_id',document.querySelector('#category').value);data.append('description',document.querySelector('#description').value);data.append('tags',document.querySelector('#tags').value);data.append('visibility',document.querySelector('#visibility').value);try{const result=await new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','ajax/upload.php');xhr.upload.onprogress=e=>{if(e.lengthComputable)bar.style.width=Math.round(e.loaded/e.total*100)+'%'};xhr.onload=()=>{try{const j=JSON.parse(xhr.responseText);xhr.status<300&&j.success?resolve(j):reject(new Error(j.message||'Upload failed'))}catch(e){reject(new Error('Unexpected server response'))}};xhr.onerror=()=>reject(new Error('Network error'));xhr.send(data)});bar.classList.add('bg-success');status.className='status text-success small';status.textContent='Uploaded successfully';ok++;}catch(e){bar.classList.add('bg-danger');status.className='status text-danger small';status.textContent=e.message;failed++;}}document.querySelector('#uploadSummary').innerHTML=`<div class="alert ${failed?'alert-warning':'alert-success'}">${ok} uploaded, ${failed} failed.</div>`;if(ok&&!failed)setTimeout(()=>location.href='assets.php',900);else upload.disabled=false;};})();
</script>
HTML;
require __DIR__.'/includes/footer.php';
?>

